### ISSUE TITLE
Rails 3 simple_audit helper not working

### ISSUE THREAD

**Issue by litch** [gtarnovan/simple_audit#1]
I am running Rails 3.0.0 on REE.  I am getting this deprecation warning:

DEPRECATION WARNING: Object#returning has been deprecated in favor of Object#tap. (called from _app_views_users_show_html_erb___2080499986_2169255960_0 at /Users/litch/code/atxent/app/views/users/show.html.erb:25)

And the line of the helper that is actually throwing that is this:
            audit.delta(older_audit).collect do |k, v| 

I then don't get changes from the helper.  My helper returned code is, for example:

<div class="audit"><div class="action update">update</div><div class="user">Justin</div><div class="timestamp">Wed, 03 Nov 2010 10:20:07 -0500</div><div class="changes"></div></div><div class="audit"><div class="action update">update</div><div class="user">Justinu</div><div class="timestamp">Wed, 03 Nov 2010 10:16:24 -0500</div><div class="changes"></div></div>

Where the changes for that particular audit were:
INSERT INTO `audits` (`action`, `auditable_id`, `auditable_type`, `change_log`, `created_at`, `updated_at`, `user_id`, `user_type`, `username`) VALUES ('update', 1, 'User', '--- \nsex_id: 2\nname: Justinu\ncreated_at: 2010-04-02 19:03:45 Z\ncrypted_password: <censored>\nupdated_at: 2010-11-03 15:16:00.850592 Z\nperishable_token: E3BnQFOuz5aTAqb6qK\nnickname: Super Justin\nfile_file_size: \nfile_content_type: \nusername: litch\nfile_updated_at: \nfile_file_name: \nid: 1\nhire_date: 2010-04-01\nregion_id: 1\npassword_salt:<censored>\ncompensation_method: \nphone:<phone>\npersistence_token:<token>\nlast_login_at: \nactive_id: \nemail: <myemail>\n', '2010-11-03 15:16:00', '2010-11-03 15:16:00', 1, 'User', 'Justinu')

**Comment by gtarnovan** [comment]
The deprecated Object#returning has been replaced with Object#tap but the update has not been packed as a gem yet.

Can you please paste the contents of all audit records for one audited model (user Justin in the above example). 

<pre>User.find(1).audits.collect(&:attributes).to_yaml</pre>


Thanks and sorry for the late answer - we've been on the move to a newoffice

**Comment by litch** [comment]
=> "--- \n- created_at: 2010-11-03 15:15:48 Z\n  change_log: \n    name: Justinu\n    sex_id: 2\n    created_at: 2010-04-02 19:03:45 Z\n    crypted_password: (hash)\n    file_content_type: \n    file_file_size: \n    nickname: Super Justin\n    perishable_token: grBEUVhMueDvi6eLxha\n    updated_at: 2010-11-03 15:15:48.596657 Z\n    file_file_name: \n    file_updated_at: \n    username: litch\n    hire_date: 2010-04-01\n    id: 1\n    compensation_method: \n    password_salt: (hash)\n    region_id: 1\n    persistence_token: (hash)\n    phone: 512 555-1212\n    active_id: \n    last_login_at: \n    email: justin@email.com\n  updated_at: 2010-11-03 15:15:48 Z\n  username: Justin\n  action: update\n  user_type: User\n  id: 19\n  user_id: 1\n  auditable_type: User\n  auditable_id: 1\n- created_at: 2010-11-03 15:16:00 Z\n  change_log: \n    name: Justinu\n    sex_id: 2\n    created_at: 2010-04-02 19:03:45 Z\n    crypted_password: (hash)\n    file_content_type: \n    file_file_size: \n    nickname: Super Justin\n    perishable_token: E3BnQFOuz5aTAqb6qK\n    updated_at: 2010-11-03 15:16:00.850592 Z\n    file_file_name: \n    file_updated_at: \n    username: litch\n    hire_date: 2010-04-01\n    id: 1\n    compensation_method: \n    password_salt: (hash)\n    region_id: 1\n    persistence_token: (hash)\n    phone: 512 555-1212\n    active_id: \n    last_login_at: \n    email: justin@email.com\n  updated_at: 2010-11-03 15:16:00 Z\n  username: Justinu\n  action: update\n  user_type: User\n  id: 20\n  user_id: 1\n  auditable_type: User\n  auditable_id: 1\n- created_at: 2010-11-03 15:16:24 Z\n  change_log: \n    name: Justin\n    sex_id: 2\n    created_at: 2010-04-02 19:03:45 Z\n    crypted_password: (hash)\n    file_content_type: \n    file_file_size: \n    nickname: Super Justin\n    perishable_token: GMAlorsWMXw1wmd4H9h\n    updated_at: 2010-11-03 15:16:24.454534 Z\n    file_file_name: \n    file_updated_at: \n    username: litch\n    hire_date: 2010-04-01\n    id: 1\n    compensation_method: \n    password_salt: (hash)\n    region_id: 1\n    persistence_token: (hash)\n    phone: 512 555-1212\n    active_id: \n    last_login_at: \n    email: justin@email.com\n  updated_at: 2010-11-03 15:16:24 Z\n  username: Justinu\n  action: update\n  user_type: User\n  id: 21\n  user_id: 1\n  auditable_type: User\n  auditable_id: 1\n- created_at: 2010-11-03 15:20:07 Z\n  change_log: \n    name: Justin\n    sex_id: 2\n    created_at: 2010-04-02 19:03:45 Z\n    crypted_password: (hash)\n    file_content_type: \n    file_file_size: \n    nickname: Super Justin\n    perishable_token: cXxOWVptglqOAnMnrwN\n    updated_at: 2010-11-03 15:20:07.797879 Z\n    file_file_name: \n    file_updated_at: \n    username: litch\n    hire_date: 2010-04-01\n    id: 1\n    compensation_method: \n    password_salt: (hash)\n    region_id: 1\n    persistence_token: (hash)\n    phone: 512 555-1212\n    active_id: \n    last_login_at: \n    email: justin@email.com\n  updated_at: 2010-11-03 15:20:07 Z\n  username: Justin\n  action: update\n  user_type: User\n  id: 22\n  user_id: 1\n  auditable_type: User\n  auditable_id: 1\n"

**Comment by litch** [comment]
and no problem, thank you for the support.  i felt like i was getting close to finding the problem, but couldn't quite get there.

**Comment by gtarnovan** [comment]
thanks for the feedback and for pointing out this issue
please update your gem to version 0.1.1

the problem was due to a change in how blocks are captured by action view in rails 3.
http://api.rubyonrails.org/classes/ActionView/Helpers/CaptureHelper.html#method-i-capture

give it a try and please do reply if the problem persists. we have finally finished our moving and I'll be able to respond quickly.

**Comment by litch** [comment]
Looks good.  I've updated it and it works well in dev, I'll deploy tomorrow morning in some planned downtime.

I would also suggest that you include a sample file for styling the output...

**Comment by gtarnovan** [comment]
glad to hear that and ... you read my mind.
i've put some sample css in the readme for now and will add a generator later on.
