### ISSUE TITLE
Suggestion - Limit the number of audits rendered

### ISSUE THREAD

**Issue by litch** [gtarnovan/simple_audit#2]
I ran into an issue where I was generating lots of audits and to speed things up wrote a modified helper method:

def render_n_audits(audited_model, number)
    return '' unless audited_model.respond_to?(:audits)
    audits = (audited_model.audits.order('audits.created_at DESC').limit(number) || []).dup
    res = ''
    audits.each_with_index do |audit, index|
      older_audit = audits[index + 1]
      res += content_tag(:div, :class => 'audit') do
        content_tag(:div, audit.action, :class => "action #{audit.action}") +
        content_tag(:div, audit.username, :class => "user") + 
        content_tag(:div, l(audit.created_at), :class => "timestamp") + 
        content_tag(:div, :class => 'changes') do
          changes = if older_audit.present?
            audit.delta(older_audit).collect do |k, v| 
              "\n" + 
              audited_model.class.human_attribute_name(k) +
              ":" +
              content_tag(:span, v.last, :class => 'current') +
              content_tag(:span, v.first, :class => 'previous') 
            end
          else
            audit.change_log.reject{|k, v| v.blank?}.collect {|k, v| "\n#{audited_model.class.human_attribute_name(k)}: #{v}"}
          end
          changes.join  
        end  
      end
    end
    res
  end

It takes advantage of some Rails 3 stuff and so may not be as broadly applicable, but I've found that even pulling all of my audit records (by setting the number to pull higher that the ones that exist) it seems to have sped things up considerably.  I don't really like mucking around in my gems and so just threw this helper method into my ApplicationHelper, but thought I'd let you know.

**Comment by gtarnovan** [comment]
Thank you for the suggestion !
A more general solution would be to add pagination to the helper. I will think about this and get back to you if I implement it in the gem.

I am curios though as how you could have seen those speed improvements. If you pulled out all audits record by setting a high limit, the only speed improvement I see is  from the audit sorting code from ruby

<pre>
audits = (audited_model.audits || []).dup.sort{|a,b| b.created_at <=> a.created_at}
</pre>


to sql

<pre>
audits = (audited_model.audits.order('audits.created_at DESC').limit(number) || []).dup
</pre>


But this could only generate distinguishable speed improvements for very high numbers of assets, which in turn would make the rendering much slower.
Please tell me how you have measured these speed improvements.

Thank you

**Comment by litch** [comment]
Yes, general pagination would probably be even better, but this works for me for now.

I was mistaken about the speed increase (which is kind of reassuring because I was confused about it as well) - I thought that since it was showing a "creation" type audit, that was the first one - however it will always display the full record for the first audit entry.

I was just testing on my dev machine (a MacBook Air that's pretty slow) and had been working on the show page of the following model:

> > Club.find(5).audits.count
> > => 702

With the regular render_audits method, I see:

<pre>
Rendered clubs/show.html.erb within layouts/application (2957.4ms)
Completed 200 OK in 3296ms (Views: 2960.4ms | ActiveRecord: 16.9ms)

Rendered clubs/show.html.erb within layouts/application (2945.2ms)
Completed 200 OK in 3290ms (Views: 2948.0ms | ActiveRecord: 14.2ms)
</pre>

Whereas with the render_n_audits(@club, 750) I see:

<pre>
Rendered clubs/show.html.erb within layouts/application (2906.7ms)
Completed 200 OK in 3078ms (Views: 2905.8ms | ActiveRecord: 16.6ms)

Rendered clubs/show.html.erb within layouts/application (2919.6ms)
Completed 200 OK in 3258ms (Views: 2919.0ms | ActiveRecord: 17.1ms)
</pre>

Not significantly different.  However turning it down to only the last 100 records, of course, I see a pretty dramatic improvement (as you would expect):

<pre>
Rendered clubs/show.html.erb within layouts/application (395.5ms)
Completed 200 OK in 724ms (Views: 400.7ms | ActiveRecord: 10.6ms)

Rendered clubs/show.html.erb within layouts/application (428.9ms)
Completed 200 OK in 598ms (Views: 434.2ms | ActiveRecord: 11.2ms)
</pre>


Phew, sanity restored.

**Comment by gtarnovan** [comment]
Oh, ok, I see the problem: the oldest audit in the trail is always displayed with all fields, looking as if it was the audit of the object's creation.
You could overcome this issue by selecting n + 1 audits from the database and displaying only the first n.
Something like this:

<pre>

def render_n_audits(audited_model, number)
    return '' unless audited_model.respond_to?(:audits)
    #    
    # select n + 1 audits
    #
    audits = (audited_model.audits.order('audits.created_at DESC').limit(number + 1) || []).dup
    res = ''
    audits.each_with_index do |audit, index|
      older_audit = audits[index + 1]
      res += content_tag(:div, :class => 'audit') do
        content_tag(:div, audit.action, :class => "action #{audit.action}") +
        content_tag(:div, audit.username, :class => "user") + 
        content_tag(:div, l(audit.created_at), :class => "timestamp") + 
        content_tag(:div, :class => 'changes') do
          changes = if older_audit.present?
            audit.delta(older_audit).collect do |k, v| 
              "\n" + 
              audited_model.class.human_attribute_name(k) +
              ":" +
              content_tag(:span, v.last, :class => 'current') +
              content_tag(:span, v.first, :class => 'previous') 
            end
          else
            audit.change_log.reject{|k, v| v.blank?}.collect {|k, v| "\n#{audited_model.class.human_attribute_name(k)}: #{v}"}
          end
          changes.join    
        end
      end
      #
      # skip entry n + 1
      #
      break if n == index + 1 
    end
    res
  end

</pre>
